"""initial_schema

Revision ID: 0d75a9572da8
Revises: 
Create Date: 2026-04-15 06:18:15.616916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0d75a9572da8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casos_netlab',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_muestra_netlab', sa.String(length=100), nullable=False),
    sa.Column('fecha_corte', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departamento_paciente', sa.String(length=100), nullable=False),
    sa.Column('provincia_paciente', sa.String(length=100), nullable=False),
    sa.Column('distrito_paciente', sa.String(length=100), nullable=False),
    sa.Column('ubigeo_paciente', sa.String(length=10), nullable=False),
    sa.Column('edad_paciente', sa.Integer(), nullable=False),
    sa.Column('sexo_paciente', sa.String(length=1), nullable=False),
    sa.Column('nombre_examen', sa.String(length=200), nullable=False),
    sa.Column('dx_molecular_dengue', sa.String(length=50), nullable=True),
    sa.Column('serotipo_dengue', sa.String(length=20), nullable=True),
    sa.Column('elisa_ns1', sa.String(length=50), nullable=True),
    sa.Column('fecha_validado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_netlab_id_muestra_netlab'), 'casos_netlab', ['id_muestra_netlab'], unique=True)
    op.create_table('casos_noti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_caso_noti', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('distrito', sa.String(length=100), nullable=False),
    sa.Column('ubigeo', sa.String(length=10), nullable=False),
    sa.Column('enfermedad', sa.String(length=150), nullable=False),
    sa.Column('ano_epidemiologico', sa.Integer(), nullable=False),
    sa.Column('semana_epidemiologica', sa.Integer(), nullable=False),
    sa.Column('tipo_diagnostico', sa.String(length=50), nullable=False),
    sa.Column('diresa_notifica', sa.String(length=150), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_noti_id_caso_noti'), 'casos_noti', ['id_caso_noti'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('reportes_app',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('tipo_lugar', sa.String(length=100), nullable=False),
    sa.Column('tipo_objeto', sa.String(length=100), nullable=False),
    sa.Column('observa_larvas', sa.String(length=10), nullable=False),
    sa.Column('conocimiento_dengue_cercano', sa.String(length=10), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # idx_reportes_app_ubicacion es creado automáticamente por GeoAlchemy2
    op.create_index(op.f('ix_reportes_app_usuario_id'), 'reportes_app', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportes_app_usuario_id'), table_name='reportes_app')
    # idx_reportes_app_ubicacion es eliminado automáticamente por GeoAlchemy2 al hacer drop_table
    op.drop_table('reportes_app')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_casos_noti_id_caso_noti'), table_name='casos_noti')
    op.drop_table('casos_noti')
    op.drop_index(op.f('ix_casos_netlab_id_muestra_netlab'), table_name='casos_netlab')
    op.drop_table('casos_netlab')
    # ### end Alembic commands ###
